# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35b9aac926ad06ff86dbfe4fe12bb75409d825f1ef4e1bbcea104e8bf952ea58cf67df9938e4fc6d46884d0a67c93a21c30160f658cbd83de5133efe68e18660

test:
  secret_key_base: 5c4e24ba413c51fb722992353c98459098339cfb80089783a01d0d644f84286876b28b2a261342567d14991b100ecf9dc93b29b3e6d7fba5e8c4c3f2689eb86c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
